server:
  port: 8080

#logging:
#  level:
#    root: DEBUG
#    org.springframework.jms: DEBUG
#    com.rabbitmq: DEBUG

management:
  endpoint.health.probes.enabled: true
  endpoints.web:
    exposure.include: "*"
    base-path: /actuator
#  health:
#    db:
#      # FIXME This should be enabled in production
#      enabled: false
#    defaults:
#      enabled: true
#  defaults:
#    metrics:
#      export:
#        enabled: true
#  tracing:
#    enabled: true
#  otlp:
#    metrics:
#      export:
#        enabled: true
#        url:  "http://localhost:4318/v1/metrics"
#        aggregation-temporality: cumulative
#    tracing:
#      export:
#        enabled: false
#    logging:
#      export:
#        enabled: true
#      endpoint: "http://localhost:3100/otlp/v1/logs"
otel:
  metric:
    export:
      interval: 15s
  exporter:
    otlp:
      metrics:
        endpoint: "http://localhost:4318/v1/metrics"
        protocol: http/protobuf
      traces:
        endpoint: "http://localhost:4318/v1/traces"
        protocol: http/protobuf
      logs:
        endpoint: "http://localhost:3100/otlp/v1/logs"
        protocol: http/protobuf
        headers:
            "Authorization": "Basic dG90bzp0b3Rv"
  instrumentation:
    common:
      default-enabled: false
    annotations:
      enabled: false
    jdbc:
      enabled: false
    logback-appender:
      enabled: true
    spring-web:
      enabled: true
    spring-webmvc:
      enabled: true
    micrometer:
      enabled: false
  metrics:
    exporter: none
  traces:
    exporter: none
  logs:
    exporter: otlp
